### PR TITLE
Include current counts

### PR DESCRIPTION
**Pull request by mrgoldy**

### CODE REVIEW

**Comment by JoshyPHP** [comment]
What's the use case for this? Under normal circumstances the *Count value will always be equal to *Limit.

**Comment by mrgoldy** [comment]
Ah, I misunderstood it then. I thought it kept counting even if the limit was reached.
And then it's possible to provide more detailed error messages if need be:
`Tag limit reached for $tagName, limit: $tagLimit, current: $tagCount`.

**Comment by JoshyPHP** [comment]
Not really. The counters keep track of valid tags. Once a limit is reached, they can't be incremented anymore because all tags get invalidated.

**Comment by mrgoldy** [comment]
Okay, then this PR is futile. Thanks for the explanation.

**Pull request closed without merging**
