### PR TITLE
Supporting bilibili, niconico and netease cloud music for MediaEmbed plugin

### PR DESCRIPTION
**Pull request by n0099**
From wikipedia:
> Bilibili, also nicknamed B Site in China, is a Chinese video sharing website based in Shanghai, themed around animation, comics, and games, where users can submit, view and add overlaid commentary on videos.

> Niconico, known before 2012 as Nico Nico Douga, is a Japanese video-sharing service on the web. "Niconico" or "nikoniko" is the Japanese ideophone for smiling. As of 2021, Niconico is the 34th most-visited website in Japan, according to Alexa Internet.

> NetEase Cloud Music is a freemium music streaming service developed and owned by NetEase, Inc. The streaming service was launched to the public on the 23 April 2013. As of April 2017, the platform has 300 million users, and a music database consisting of more than over 10 million songs.

### CODE REVIEW

**Comment by n0099** [comment]
Also I found out this website: https://iframely.com/domains/niconico, which is helpful to figure out does websites providing iframe-based embed url.

**Review by BANKA2017 — APPROVED** [review]
look good for me

**Comment by JoshyPHP** [comment]
Hi,

Thanks for your interest in the s9e\TextFormatter library. Unfortunately, I won't be adding those sites to the default list of preconfigured sites because I can't maintain them easily. If you're looking for a way to add those sites for your own use, the best way would be through [the configurator API](https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/). I only use the XML files during development and they are [not distributed in archive form](https://github.com/s9e/TextFormatter/blob/d115085898f41bfe251b303d690ccfdc35fc12b2/.gitattributes#L13), instead the PHP files are patched by [patchCachedSiteDefinitionCollection.php](https://github.com/s9e/TextFormatter/blob/d115085898f41bfe251b303d690ccfdc35fc12b2/scripts/patchCachedSiteDefinitionCollection.php). If you still want to use the XML files for yourself, you can read them using the `XmlFileDefinitionCollection` class. You can also add their configuration to the default list of sites at runtime, if that makes sense for your use case. Here's an example:

```php
use s9e\TextFormatter\Plugins\MediaEmbed\Configurator\Collections\XmlFileDefinitionCollection;

$configurator = new s9e\TextFormatter\Configurator;

// Add all sites from given dir to the default list
$mySites = new XmlFileDefinitionCollection('/path/to/sites');
foreach ($mySites as $siteId => $siteConfig)
{
	$configurator->MediaEmbed->defaultSites[$siteId] = $siteConfig;

	// Or you could add the site directly, that works too
	//$configurator->MediaEmbed->add($siteId, $siteConfig);
}

// The new sites are available directly
$configurator->MediaEmbed->add('bilibili');

extract($configurator->finalize());

$text = 'https://www.bilibili.com/video/BV1xx411c7mD';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<span data-s9e-mediaembed="bilibili" style="display:inline-block;width:100%;max-width:640px"><span style="display:block;overflow:hidden;position:relative;padding-bottom:75%"><iframe allowfullscreen="" loading="lazy" scrolling="no" src="https://player.bilibili.com/player.html?aid=&amp;bvid=BV1xx411c7mD&amp;page=&amp;high_quality=1" style="border:0;height:100%;left:0;position:absolute;width:100%"></iframe></span></span>
```

Note that if you edit XML files manually, you'll have to properly escape special characters. That's why I use the `(?'name')` form for named subpatterns in regexp.

**Comment by n0099** [comment]
Although `music.163.com/outchain/player` is randomly requesting user to login in order to show the player (which is not possible due to they set samesite attribute on their account session cookies), other embed url are not changed for years and very stable to use, if it's broken in the future I will notice and make a new pr.

**Comment by n0099** [comment]
And these websites is popular in china and japan, in https://github.com/s9e/TextFormatter/tree/master/src/Plugins/MediaEmbed/Configurator/sites there's only one website youku.com is mainly used by chinese, but nowadays youku is not very attractive for users to upload their ugc videos, so I think there's fewer chance to see a link to youku video rather than bilibili in wide forums.

So I think forums based on phpbb, xenforo and flarum which using their extension/plugin to integrated with s9e\TextFormatter will be benefitted by add these sites in default sites list since it's common links posts by chinese and japanese.

**Pull request closed without merging**
