### PR TITLE
Autolink trimUrl underscore fix

### PR DESCRIPTION
**Pull request by w-4**
### Fixes Bug:  

the url: https://www.example.com/test_ would be trimmed to https://www.example.com/test.
this commit prevents it. 
I also removed the additional punctuation match \p{P} in the php file - don't think it's needed now, but let me know if it is.

### CODE REVIEW

**Comment by JoshyPHP** [comment]
I'm generally reluctant to add exceptions. For instance, the reason I keep trailing dashes is because of YouTube URLs. Is there a specific kind of URLs that end with an underscore?

I'm going to add a test for Unicode punctuation. As I recall, the main use case for trimming Unicode punctuation marks is to better support the Japanese quotation marks 「」. The real reason there wasn't a test for it until now is because they're not supported by the JavaScript parser and I didn't want to have a test whose results differ depending on the language.

**Comment by w-4** [comment]
Yep, examples are instagram and twitter links, the username can have trailing underscores.

Regarding the punctuation match, the way it is now the javascript and php parser would differ in their output in some cases. f.e. 
https://www.example.com/#/ would be left unchanged in js and would become https://www.example.com/ in php.

**Comment by JoshyPHP** [comment]
Alright, I'm going to think about it and I'll update this entry when I take a decision.

If you have actual examples of URLs that end with an underscore, please feel free to post them here as it helps gathering actual use cases.

**Comment by w-4** [comment]
sure, here are some examples:
https://twitter.com/test_
https://www.instagram.com/test_/

**Pull request closed without merging**
